# (PART\*) Part I. R Programming Basics {-}

# Data in R

## Operators  

Let us start with the basic. Almost all programming languages can be used as a calculator. You can use the `+`, `-`, `*` and `/` symbols to perform addition, subtraction, multiplication and division between two numeric values. These are called _arithmetic operators_. Type the following lines of code on the RStudio console pane and check the results of these operations:
```r
2 + 2
10 - 5
4.5*3
4/2
```
The `[1]` in front of the results indicates that the value after it is the first value of the result for that operation.

Some other arithmetic operators are `^` or `**` for exponentiation, `%%` [modulus](https://www.khanacademy.org/computing/computer-science/cryptography/modarithmetic/a/what-is-modular-arithmetic) and `%/%` for [integer division](https://mathworld.wolfram.com/IntegerDivision.html). 

_Logical operators_ perform comparison between two values. Logical operators return either `TRUE` or `FALSE`. Type and run the following lines of code and check the results:
```r
5 < 4 # less than
2 > 1 # greater than
2==1  # exactly equal to
5>=5  # greater than and equal to
5!=6  # not equal to
```

A very useful __binary operator__ in R is denoted by the colon `:`. Binary operators are operators that perform actions with two values. The colon operator generates regular sequences. It can also create sequence in reverse order. Whether the sequence is increasing or decreasing depends whether the value before the operator is less than or greater than the value after the operator. 
```r
1:15
15:1
```

## Objects  

### Creating Objects  
The power of programming lies in its ability to not only manipulate numeric values but also textual values. Any value can be stored as an object in a computer program and then referenced later for further manipulation. The _assignment operator_, `<-`, is used to assign a value to an object. It comprises the less than symbol `<` and a hyphen `-`. Manipulation to the value can be done by manipulating the object. 
```r
a <- 5
a+5
a*2.5
a>=5
```
Object provide a way of storing data with a descriptive name such that the programs can be easily read and understood by its readers. For example, we can create an object `aapl`, which is the ticker for the company Apple Inc. and assign it a value of `274.5b`, which is Apple's revenue in billions for the year 2020. Now, every time you type `aapl` on the console, it will print `274.5b`, unless you reassign a different value to this object. 
```r
aapl <- "274.5b"
aapl
```

Note: `=` can also be used as an assignment operator but is not recommended for R.In some cases it is forbidden. 

### Naming Objects  
Naming an object is a not that easy. You want the name to be meaningful and easily understood but not very lengthy. Objects with multiple words can be created by joining them with an underscore or a dot. You can also capitalize the different words. Object names cannot start with a number or a dot. Avoid using alphanumeric character in object names. 

Most importantly do not use a name that has already been assigned to some other value, unless you have good reason to do so. For example, variable `pi` exists in R by default. So does keyword variables like `TRUE`, `FALSE`, `NA`, etc. Do not use these names while creating an object. Doing so will override their default value and you have to restart the R session to revert back. 
```r
pi
TRUE
FALSE
NA
```
R is case sensitive meaning `TRUE` and `True` are not the same. Try it yourself and see what you get!

So far, you have created two objects, `a` and `aapl`. In the top right hand pane of RStudio, you will see these two objects listed on the 'Environment' tab. If you click on the down arrow by the `List` icon and select `Grid` view, you will see additional details about these objects such as type, length, size and value. 

## Data Types

Lets look at the type in detail because it is very important to know how R deals with different types of data. Type of an object, also known as its data type, tells us the kind of operations that is possible with that object. For example, `a` has numeric data type and therefore arithmetic operations can be performed to it. `aapl` is of character type and thus arithmetic operators cannot be applied to it. If you do, you will receive an error: 
```r
aapl+1
aapl*3
aapl/3
```
The error message tells you that you are applying a binary operator to a non-numeric value. 

Four types of basic data types we will focus on are - numeric, integer, logical, and character. 

### Numeric  
Numeric data are contains decimal numbers. Although, it may also include values without decimal numbers. In most cases, numeric data is chosen by default in R for numeric values. 

### Integer
Integer are whole numbers, meaning numbers without decimal. 

R provides numerous functions to check the data type of an object and to modify it as well.
```r
is.numeric(a)
is.integer(a)
```
Notice the results of the two operations. Even though `a` does not have any decimal point, R has stored it as numeric instead of integer type. While R is able to automatically distinguish data types in most cases, often you will have to explicitly tell R which data type you want for a given object. 
```r
a <- as.integer(a)
is.integer(a)
```

### Logical  
Logical data take either `TRUE` or `FALSE` values. Logical data type result from logical operations:
```r
logical_expression <- (a > 5)
is.logical(logical_expression)
```
`NA` is also considered to be of logical data type and signifies missing or null values. It is a special type of logical. 
```r
is.logical(NA)
```

### Character 
Finally, character data types represent string. String in computer program refers to any letter, digit, punctuation and extra characters enclosed inside quotation marks. 
`aapl`, on the other hand, is stored as character because while creating this object we enclosed its values in quotation marks. 
```r
is.character(aapl)
```
Data type modifications must be done with careful consideration to avoid unexpected results. For example, note the data loss occurred as a result of the following data type conversions below:
```r
as.integer(5.9)
as.numeric(aapl)
```

## Data Structures  
Now that you have been introduced to objects and data types, let's look at some of the main data structures provided by R to store real world data. 

### Vectors  
Vectors are the simplest data structure in R. So far the objects we have created are __scalar__ vectors, scalar because they contain a single value. Vectors with more than one value can be created as follows:
```r
revenue = c(274.5, 143.5)
print(revenue)
is.vector(a)
```
Vectors can contains any data type but it must all be of the same type. In other words, a vector cannot have mixtures of data types. There is one exception - `NA` can be included within vectors of any other data type to denote missing data in that vector.

### Matrices and Arrays
A Matrix is a vector that has additional attributes called dimensions. Matrices have only two dimensions. Arrays are multidimensional. Again, all elements in a matrix or array must be of same data type.  

Matrix and array can be created by using the `matrix()` and `array()` functions. Below is a use-case:
```r
amatrix <- matrix(1:6, nrow = 3, byrow=TRUE)
print(amatrix)
```
The above line of code creates a matrix containing numbers from 1 to 6, as indicated by `1:6`. It has three rows, as indicated by `nrow = 3` and the values 1 through 6 are filled row-wise, as indicated by `byrow = TRUE`. You may define the number of columns as well using `ncol=2`. However, if you don',t R will try to figure it out based on the number of values you passed. 

It can be useful to give row and column names when working with a matrix. 
```r
rownames(amatrix) = c('row1', 'row2', 'row3')
colnames(amatrix) = c('col1', 'col2')
print(amatrix)
```

Matrix operation can be performed by using the arithmetic operator on matrices. 
```r
amatrix + 10       # add scalar to each element
amatrix * 2        # multiply each element by scalar
amatrix + amatrix  # matrix addition
amatrix * amatrix  # element by element products
```
Matrix multiplication can be performed using `%*%` as long as it is possible:
```r
bmatrix <- matrix(1:4, nrow=2)
amatrix%*%bmatrix
```

When using the array function, the number of dimensions can be defined using `dim`:
```r
my_array <- array(1:12, dim = c(2, 3, 4))
print(my_array)
```
The above example creates a 3 dimensional array. It has two rows, three columns and four of those 2x3 matrices.

### Lists  
Lists are useful because they can store multiple data types inside of it. In fact we can even store matrices and arrays if we need to. 
```r
my_list <- list(aapl, amatrix, my_array)
print(my_list)
```

### Data frames  