# (APPENDIX) Appendix {-}

# Install R and RStudio {#starting}

To begin using R you will need to install R as well as RStudio, which is an integrated development environment (IDE) for R. Both are available for Windows, Mac or Linux. To download R, go to the [Comprehensive R Archive Network](https://cran.r-project.org/) (CRAN).

__Note:__ Administrative privileges will be needed to install new software on your computer. 

## Windows  
Once on the [CRAN](https://cran.r-project.org/) page, click the "Download R for Windows" link and then click either the "base" link or the "install R for the first time" link. Next, click the first link at the top of the page, which should be the latest version of R for Windows. As of this writing, R4.1.1 is the latest version of R for Windows. An installer program will be downloaded. Click and run the installation wizard from your Downloads folder. Upon completion, R will be installed into your Program Files folders and a shortcut to R will also be placed in your Start menu. 

## Mac  
Once on the [CRAN](https://cran.r-project.org/) page, click the "Download R for Mac" link. The top of the page will have information on the latest version of R for Mac. There will also be download instructions if you are using terminal. Otherwise, right below there will be a package link (with a .pkg extension) to the latest version of R for each macOS version. As of this writing, the latest R for Mac version package is R-4.1.0.pkg. You will see multiple links with same version. Click the one which corresponds to your macOS version. An installer program will be downloaded. Click and run the installation wizard from your Downloads folder. Choose the default options, which are suitable for most users. 

## Linux 
R comes preinstalled on many Linux system. To upgrade to the newest version of R, go to the [CRAN](https://cran.r-project.org/) page and click the "Download R for Linux" link. Choose and click the linux system you have and follow the directory trail to the version of Linux you wish to install on. 

# Install RStudio

R is a computer language. To run programs written in R you will need a tool that your computer can use to interpret R. This can be a UNIX terminal. However, RStudio is more popular due to its easy-to-use interface. You can also use other IDE of your choice, given it is R compatible. 

There are two versions of RStudio, Desktop and Server, available to download for free. Choose the Desktop version by clicking on "Download RStudio Desktop" link on the [Rstudio products](https://www.rstudio.com/products/rstudio/) page. Follow the instructions to complete the installation. Once completed, you can use RStudio as most other programs in your computer by simply opening RStudio.

When you open RStudio, you will see three panes. The largest pane is the console window, which is exactly the same as what you would see if you opened R application. This is where you will write your R codes and run them. The remaining two panes serve as text editor, graphics window, debugger, file manager, package manager and much more. You will learn about these functions as we require them. 

ADD MORE ON HOW TO USE RSTUDIO

__Note:__ When a new release of the R and/or RStudio is available for your computer, you can follow the same installation process to upgrade to the new version of the software. 

<!-- # Run R and RStudio in the cloud -->

# R packages

## Installing R packages

R comes preloaded with many useful functions. In addition, many people share useful functions they have developed as a package through CRAN and github. These packages will need to be installed on your computer before you can begin using them. The easiest way to install an R package is to use the `install.packages` function.

For example, type and run the following line of code in console window of RStudio to install the `ggplot2` package:  
```r
install.packages('ggplot2')
```

You can also install multiple packages at once by inputting them as an R list:  
```r
install.packages( c('dplyr', 'tidyr', 'stringr') )
```

Often there are many packages that have very similar purpose. You will need to do a bit of research to know which packages might be the best for you. [R-packages mailing list](https://www.r-bloggers.com/), [R-bloggers](https://www.r-bloggers.com/) and [RStudio support](http://support.rstudio.com.) are some places you can go to obtain valuable information about R packages. 

## Loading R packages  
Once the packages are installed, every time you want to use it you will need to load them. The reason for installing and loading packages is to prevent R from becoming slow, by having only those programs that you need instead of everything that is available out there for use. 

To load an R package into the R environment you are working on, use the `library` function:
```r
library(ggplot2)
```
Note that you no longer need to use the quotation marks here. 

## Updating R package  
Catching bugs, improving performance and updating programs are important part of software maintenance. Thus, package authors occasionally release a new version of their packages. You will need to update the packages version in order to take advantage of improvements made to those packages. To do so, R provide the `update.packages` function:
```r
update.packages( c('dplyr', 'tidyr', 'stringr') )
```
Restarting R session is required after updating packages. Simply close RStudio and reopen it to begin using the updated version of the packages.  

# R online learning resources

* R Programming
    * [Hands-on Programming with R](https://rstudio-education.github.io/hopr/) (for absolute beginners, i.e., if you have never programmed before)
    * [R for Data Science](https://r4ds.had.co.nz/) (learn how to manipulate, analyze and visualize data using R’s Tidyverse packages)
    * [Advanced R](https://adv-r.hadley.nz/) (if you plan to be really good at R)
    * [R Graphics Cookbook](https://r-graphics.org/)
    * [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/)
    * [The R Graph Gallery](https://www.r-graph-gallery.com/) (R graph samples with code)
    * [R Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/) (cheat sheets for many popular R packages)

    
* R for Empirical Analysis
    * [Introduction to Econometrics with R](https://www.econometrics-with-r.org/)
    * [Forecasting: Principles and Practice](https://otexts.com/fpp2/)
    * [Financial Engineering Analytics: A Practice Manual Using R](https://bookdown.org/wfoote01/faur/)

* R and Machine Learning
    * [An Introduction to Statistical Learning / with Applications in R](https://www.statlearning.com/) (you can download the book and its R code)
    * [R Interface to Tensorflow](https://tensorflow.rstudio.com/) (deep learning in R)
        
* Other Tutorials on Econometrics & Statistics using R
    * [A Short R Tutorial](https://data.princeton.edu/R) by Germán Rodríguez
    * [Introductory Econometrics Examples](https://justinmshea.github.io/wooldridge/articles/Introductory-Econometrics-Examples.html) (data and examples from Wooldridge)
    * [STAT545](https://stat545.com/) by [Jenny Bryan](https://jennybryan.org/) : Data wrangling, exploration, and analysis with R