---
title: "Intro to R"
Author: "TDMDAL"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    config:
      toc:
        before: |
          <li><a href="./">Intro to R</a></li>
      sharing: no
    github-repo: tdmdal/r-intro
---

# Welcome to Intro to R for Business{-}

## What's R {-}

R is a powerful computer language for statistical computing. R is free, open source and available on every major platform. R has a huge set of packages for statistical modelling, machine learning, visualization as well as for communicating the results of your analysis in the form of beautiful interactive apps. RStudio, the Integrated Development Environment (IDE), provides a tailored space for data science needs such as effective data handling and storage, interactive data analysis, implementing statistical and machine learning techniques and graphical facilities. 

R also has a diverse and welcoming community such as the R meetups and #rstats twitter community. 

For more information on R, visit the official [R-project](https://www.r-project.org/about.html) website.


## About this site {-}

Intro to R for Business is a companion site for your Intro to R workshops, a prerequisite for select courses within Rotman programs. This site provides information on the workshops, items covered during the workshops, additional resources such as practice questions, links to other R books and tutorial to aid for further learning.

As with any language the initial learning curve can be steep. So we advise that you use R often and regularly to maintain momentum and build your R skill.  

## R Workshop {-}

### Event details {-}

**Intro to Data Analysis (in R)**

**Session 1**  
**Date:** Thursday, September 16, 2021  
**Time:** 6:00 PM - 8:00 PM (EST)  
**Location:** Online  
 
**Session 2**  
**Date:** Thursday, September 23, 2021  
**Time:** 6:00 PM - 8:00 PM (EST)  
**Location:** Online  

**Contact:** 
**Organizer:** Valeria Sladojevic-Sola; Val.Sladojevic.Sola@rotman.utoronto.ca   
**Workshop Lead:** Gerhard Trippen; Gerhard.Trippen@rotman.utoronto.ca  

### Syllabus {-}
This R workshop will introduce students to the basics of the R coding language. It allows students plenty of hands-on programming using R. The practical component includes projects that teach students to load data, assemble and disassemble data objects, navigate R’s environment system, write their own functions, and use all of R’s programming tools, such as 'if else' statements and for 'loops'. Furthermore, the workshop will teach not just how to program with R, but how to use the programming skills to support your work as a data scientist.

Topics included are:

- The very basics of R
- Packages and help pages
- R objects
- R notation
- Modifying values and programs
- Functions
- Plotting
- Data frames
- Programs